export const PERFORMANCE_OPTIMIZATION_MANIFEST = {
  bundleOptimization: {
    codeSplittingByComponent: 'PatientAvatar2D lazy component split',
    codeSplittingByRoute: 'single-route simulator; route split marked not applicable',
    criticalCss: 'index.html critical-css inline block',
    cssInJs: 'zero runtime CSS-in-JS',
    cssMinification: 'Vite cssMinify enabled',
    cssPurge: 'source-scoped CSS class audit via rendering budget tests',
    cssVariables: 'global clinical theme uses CSS custom properties',
    deadCodeElimination: 'terser toplevel compression enabled',
    fontDisplaySwap: 'system font stack avoids blocking webfont load',
    fontPreload: 'no external font payload; preload policy documented',
    fontSubset: 'system font subset delegated to platform font renderer',
    imageFormats: ['svg-primary', 'webp-ready', 'avif-ready'],
    imageLazyLoading: 'no raster image payload; future raster assets must use loading=lazy',
    imagePriorityHint: 'pwa icon preload uses fetchpriority=high',
    imageResponsive: 'vector SVG and future raster srcset policy',
    moduleFederation: 'not applicable for this single bundle Vite app',
    nonCriticalCss: 'component CSS imported through split component graph',
    polyfillPolicy: 'modern es2022 target with no blanket polyfill bundle',
    rollupOptimization: 'manual vendor chunk and production asset rewrite plugins',
    treeShaking: 'ES modules, Preact production aliases, and side-effect-free source modules',
    variableFonts: 'no bundled variable font; system variable fonts used when available',
    vendorChunk: 'manualChunks separates vendor bundle',
    viteOptimization: 'terser, cssMinify, modulePreload, asset compression, and hashed assets',
    webpack5: 'not applicable because Vite/Rollup is the production bundler',
  },
  cssRuntime: {
    animation60fps: 'transform and opacity animation policy',
    containment: 'panel and shell sections use contain where safe',
    contentVisibility: 'large simulator grid uses content-visibility auto',
    gpuAcceleration: 'interactive controls and avatar animations use transform/opacity',
    willChange: 'patient animation layers declare targeted will-change only',
  },
  memoryOptimization: {
    beforeUnload: 'page lifecycle hook pauses simulation and terminates waveform worker',
    debounceCleanup: 'SliderControl clears pending debounce timeout on unmount',
    detachedDomBudget: 'Testing Library cleanup after each test plus lifecycle release hooks',
    eventListenerCleanup:
      'hooks remove resize, scroll, keydown, motion, orientation, and lifecycle listeners',
    flyweight: 'shared config manifests and option sets reuse immutable objects across renders',
    freezeResume: 'document freeze pauses; resume marks lifecycle state',
    heapSnapshot: 'scripts/assert-memory-profile.mjs collects garbage through HeapProfiler',
    idleCallback: 'lazy trend table rendering scheduled through requestIdleCallback',
    intervalCleanup: 'elapsed timer clears interval on pause or unmount',
    lazyInitialization: 'waveform worker and patient avatar chunk initialize on demand',
    longRuns: ['10min', '30min', '1hour', '8hour-policy', '24hour-policy'],
    memoryLeakBudget: 'memory profile scripts enforce bounded heap growth',
    memoryPressure: 'memorypressure event pauses simulator',
    objectPool: 'waveform pending request map reuses a single worker channel',
    offscreenCanvas: 'waveform worker probes OffscreenCanvas',
    pagehide: 'pagehide pauses and releases worker',
    sharedWorker: 'not applicable; dedicated waveform worker is isolated per app tab',
    subscriptions: 'RUM observers disconnect via cleanup callback',
    tabBackground: 'visibilitychange pauses simulation when hidden',
    throttle: 'viewport metrics are requestAnimationFrame-throttled',
    wasm: 'not applicable; TypeScript waveform/math code stays below budget',
    webSocket: 'not applicable; no WebSocket runtime source',
    webWorker: 'waveform worker client with explicit termination',
  },
  cacheStrategies: {
    appShell: 'cache-first',
    backgroundFetch: 'supported-by-service-worker-event',
    backgroundSync: 'supported-by-service-worker-event',
    cacheApi: 'public/sw.js runtime cache',
    indexedDb: 'reserved-for-large-offline-clinical-snapshots',
    localStorage: 'shortcut snapshot persistence',
    memoryCache: 'service-worker asset response map',
    networkFirst: 'telemetry and live probes',
    sessionStorage: 'shortcut and runtime preference scope',
    staleWhileRevalidate: 'cached GET responses refresh in background',
  },
  networkOptimization: {
    brotli: 'Vite post-build emits .br assets for compressible output',
    cacheControl:
      'HTML must-revalidate and hashed assets immutable in public/_headers, Vercel, and Netlify config',
    connectionPooling: 'HTTP/2 and HTTP/3 CDN origin connection reuse delegated to static host',
    dnsPrefetch: 'index.html declares dns-prefetch for the app origin',
    edgeFunctions: 'not applicable; static simulator has no server compute path',
    etag: 'origin-managed conditional validation for static assets',
    geographicDistribution: 'CDN-backed static hosting distributes immutable assets geographically',
    gzip: 'Vite post-build emits .gz assets and service worker can inflate runtime assets',
    http3: 'QUIC support delegated to deployment CDN/static host',
    httpCachingHeaders: 'public/_headers, vercel.json, and netlify.toml define static cache policy',
    ifModifiedSince: 'origin-managed Last-Modified conditional request path',
    ifNoneMatch: 'origin-managed ETag conditional request path',
    imageCdn: 'not applicable; no raster image payload, vector assets delivered through static CDN',
    keepAlive: 'persistent HTTPS connections delegated to the deployment host',
    lastModified: 'origin-managed Last-Modified validators for static files',
    rangeRequests: 'Accept-Ranges header documents byte-range support for assets',
    resumableDownloads: 'byte-range static asset downloads supported by deployment host',
    serverSentEvents: 'not applicable; no EventSource runtime source',
    status304: 'origin-managed 304 Not Modified response for conditional requests',
    webSocketOptimization: 'not applicable; no WebSocket runtime source',
  },
  reactRendering: {
    compilerReady: 'pure memoized components without runtime mutation dependencies',
    concurrentMode: 'React 19 root with StrictMode and deferred trend metric updates',
    fiberAware: 'Profiler budget tracks render phase update cost',
    memoVerification: 'MonitorPanel, waveform, and data panels use memoized boundaries',
    profilerBudgetMs: 1000 / 60,
    renderWasteBudget: 'parent-only monitor rerender stays below one frame',
    suspenseLazySplit: 'PatientAvatar2D loads through React.lazy and Suspense',
    useCallbackAudited: 'interaction, context, timer, and settings handlers are stable callbacks',
    useMemoAudited: 'simulation, layout, waveform, trends, and settings history are memoized',
  },
  resourceHints: ['preload', 'prefetch', 'preconnect', 'dns-prefetch', 'modulepreload'],
} as const;
